codealong-empty-project/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace codealong_pie_project.Controllers
{
    public class ContactController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

codealong-empty-project/Controllers/PieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using codealong_pie_project.Models;
using codealong_pie_project.ViewModels;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace codealong_pie_project.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository pieRepository;
        private readonly ICategoryRepository categoryRepository;

        public PieController(IPieRepository pieRep, ICategoryRepository categoryRep)
        {
            pieRepository = pieRep;
            categoryRepository = categoryRep;

        }
        //public ViewResult List() //viewresult - inbyggd typ för view
        //{
        //    PieListViewModel pieListViewModel = new PieListViewModel(); //istället för viewbag, vanlig klass med properties
        //    pieListViewModel.Pies = pieRepository.AllPies;
        //    pieListViewModel.StoreName = "Jossans pajer!";
        //    return View(pieListViewModel); //skickar med hela objektet

        //    //ViewBag.StoreName = "Jossans pajer!";
        //    //return View(pieRepository.AllPies); //Kan bara skicka med en parameter/data

        //}
        //byter ut list-metod till att kunna ta parameter category
        public ViewResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            //ingen spec cat vald
            if (string.IsNullOrEmpty(category))
            {
                pies = pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All pies";
            }
            else
            {
                pies = pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PieId);
                currentCategory = categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category)?.CategoryName;
            }

            return View(new PieListViewModel
            {
                Pies = pies,
                CurrentCategory = currentCategory
            });
        }
        public  IActionResult Details(int id)
        {
            var pie = pieRepository.GetPieById(id); //hämtar paj med rätt id med pierepositorys metod (firstordefault från db)
            if (pie == null)//om pajen inte kan hämtas blir värdet null
                return NotFound(); //returnerar 404 sida
            return View(pie);
        }
        
    }
}

codealong-empty-project/Views/Shared/_Carousel.cshtml
@*copy-paste*@
<div class="row carousel-holder">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

codealong-empty-project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/Content/site.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        @*copy-paste*@
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span> @*screen-reader-shit*@
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        @*<li><a asp-controller="Pie" asp-action="List">Pies</a></li>*@
                        @await Component.InvokeAsync("CategoryMenu")
                        <li><a asp-controller="ShoppingCart" asp-action="Index">Shopping Cart</a></li>
                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                        @*Visas som li-element, invokes view component*@
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-3">
                <p class="lead">
                    @*Home eller Pie controller vad blir skillnaden?*@
                    <a asp-controller="Home" asp-action="Index"><img class="img-responsive" alt="Bethany's Pie Shop'" src="~/Images/bethanylogo.png" /></a>
                    @*<h1>@Model.StoreName </h1> ViewModel property*@
                </p>
            </div>
            <div class="col-md-9">
                @RenderBody() @*Metod i abstr klassen RazorPage*@


            </div>
        </div>
    </div>
    @* Behövs av layout sidorna *@
    @* "In layout pages, renders the content of the section named name." *@
    @RenderSection("Scripts", required: false)
</body>
</html>

codealong-empty-project/Views/Shared/_PieCard.cshtml
@model Pie

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        @*ist för pie-instans i foreach (pie in model.pies) används Model *@
        <img src="@Model.ImageThumbnailUrl" alt="">
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Pie" asp-action="Details" asp-route-id="@Model.PieId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary"
                   asp-controller="ShoppingCart"
                   asp-action="AddToShoppingCart"
                   asp-route-pieId="@Model.PieId">Add to cart</a>
            </p>
        </div>
    </div>
</div>